/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32g070xx.h"

void timer_config()
{
	RCC->APBENR1=(1U<<1);//CLK FOR TIM3
	TIM3->PSC=1600;
	TIM3->ARR=50000;
	TIM3->CNT=0;
	TIM3->CR1=(1U<<0);
	TIM3->DIER=(1U<<0);//ENABLE INTERRUPT
}

void TIM3_IRQHandler(void)
{
	TIM3->SR&=~(1<<0);
	GPIOA->ODR^=(1U<<5);
}

void delay(unsigned int a)
{
	unsigned int i,j;
	for(i=0;i<a;i++)
		for(j=0;j<600;j++);
}
int main()
{
	RCC->IOPENR=(1U<<0)|(1U<<1);//ENABLE CLOCK FOR GPIO A AND GPIOA B

	GPIOA->MODER|=(1U<<10);//CONFIG PA5 AS O/P
	GPIOA->MODER&=~(1U<<11);//ENABLE PULLUP ON PA0

	GPIOB->MODER|=(1U<<28);//CONFIG PB14 AS O/P
	GPIOB->MODER&=~(1U<<29);
	timer_config();

	NVIC_EnableIRQ(TIM3_IRQn);
	while(1)
	{
		GPIOB->ODR^=(1U<<14);
		delay(400);
	}

	//while(1)
	//{
	//	while(!(TIM3->SR&(1U<<0)));
	//	GPIOA->ODR^=(1U<<5);
	//	TIM3->SR&=~(1U<<0);
	//}
}
