/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32g070xx.h"

void delay(unsigned int a)
{
	for(int i=0;i<a;i++)
		for(int j=0;j<600;j++);
}

int main(void)
{
	RCC->IOPENR=(1U<<0);
	RCC->APBENR1=(1U<<1);
	GPIOA->MODER|=(1U<<13);
	GPIOA->MODER&=~(1U<<12);

	GPIOA->AFR[0]|=0X01000000;

	uint32_t i=0;
	TIM3->PSC=0;
	TIM3->ARR=65535;
	TIM3->CNT=0;
	TIM3->CCMR1|=(1<<5)|(1<<6);
	TIM3->CCER=1;

	TIM3->CR1=1;

	while(1)
	{
		while(i<65535)
		{
			TIM3->CCR1=i;
			i+=100;
			delay(1);
		}
		while(i>0)
		{
			TIM3->CCR1=i;
			i-=100;
			delay(1);
		}
	}
}
